name: Flutter Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build Flutter App
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Set up Ruby for iOS build
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios && pod install && cd ..

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload Android APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Build iOS App
        env:
          CI: true
        run: flutter build ios --no-codesign

      - name: Upload iOS App Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-app
          path: build/ios/iphoneos/*.app
